In [18]:
import numpy as np
import pandas as pd 

### Initialize Numpy Array

In [19]:
list = [1, 2, 3]
array = np.array(list)
array

array([1, 2, 3])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

### Sort Array

In [24]:
sorter = np.array([4, 3, 2, 1])
np.sort(sorter)

array([1, 2, 3, 4])

### Concatenate Arrays

In [25]:
l1 = np.array([1, 2, 3])
l2 = np.array([4, 5, 6])
np.concatenate((l1, l2), axis=0)

array([1, 2, 3, 4, 5, 6])

### Shape, Size, Reshape

In [26]:
list = np.array([[1, 2], [3, 4]])
list.ndim

2

In [27]:
list.size

4

In [28]:
list.shape

(2, 2)

In [29]:
list = np.arange(6)
list.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

### Indexing and Slicing

In [30]:
array = np.array([1, 2, 3, 4])
array[0]

1

In [31]:
array[0:2]

array([1, 2])

In [32]:
array[1:]

array([2, 3, 4])

In [33]:
array[:-2]

array([1, 2])

In [34]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[a > 6]

array([ 7,  8,  9, 10, 11, 12])

In [35]:
divisible5 = (a % 5 == 0)
a[divisible5]

array([ 5, 10])

In [36]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
array2 = array1[3:7]
array2


array([4, 5, 6, 7])

### Array Stacks

In [37]:
array1 = np.array([[1, 1], [2, 2]])
array2 = np.array([[3, 3], [4, 4]])
np.hstack((array1, array2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [38]:
np.vstack((array1, array2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

### Copy

In [39]:
array3 = array2.copy()
array3

array([[3, 3],
       [4, 4]])

### Array Operations

In [40]:
a = np.array([1, 2])
b = np.array([3, 4])
a + b

array([4, 6])

In [41]:
(3 * a) + (b - 4)

array([2, 6])

In [42]:
b.sum(axis=0)

7

In [43]:
b.max()

4

In [44]:
np.square(b)

array([ 9, 16])

### Matrices

In [45]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
data[0:2, 0]

array([1, 3])

In [47]:
rng = np.random.default_rng()
rng.random((4, 3))

array([[0.14409472, 0.23388174, 0.45915052],
       [0.01619471, 0.3255839 , 0.76068214],
       [0.86086486, 0.98356679, 0.23616814],
       [0.2644322 , 0.52118981, 0.6857273 ]])

### Unique and Count

In [48]:
array = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique = np.unique(array)
unique

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
unique, indices = np.unique(array, return_index=True)
indices

array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14])

In [50]:
unique, counts = np.unique(array, return_counts=True)
counts

array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1])

### Reshaping Arrays

In [51]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [53]:
np.flip(arr)

array([[5, 4, 3],
       [2, 1, 0]])

In [54]:
np.flip(arr, axis=0)

array([[3, 4, 5],
       [0, 1, 2]])

In [55]:
np.flip(arr, axis=1)

array([[2, 1, 0],
       [5, 4, 3]])

In [56]:
np.flip(arr[:,1])

array([4, 1])

In [57]:
arr.flatten()

array([0, 1, 2, 3, 4, 5])

### Loading and Saving

In [58]:
a = np.arange(6)
np.save('filename', a)

In [59]:
np.load('filename.npy')

array([0, 1, 2, 3, 4, 5])

In [60]:
np.savetxt('filename.csv', a)

In [61]:
np.loadtxt('filename.csv')

array([0., 1., 2., 3., 4., 5.])