In [34]:
import numpy as np
import pandas as pd

### Initialize Numpy Array

In [35]:
list = [1, 2, 3]
array = np.array(list)
array

array([1, 2, 3])

In [36]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

### Sort Array

In [40]:
sorter = np.array([4, 3, 2, 1])
np.sort(sorter)

array([1, 2, 3, 4])

### Concatenate Arrays

In [41]:
l1 = np.array([1, 2, 3])
l2 = np.array([4, 5, 6])
np.concatenate((l1, l2), axis=0)

array([1, 2, 3, 4, 5, 6])

### Shape, Size, Reshape

In [42]:
list = np.array([[1, 2], [3, 4]])
list.ndim

2

In [43]:
list.size

4

In [44]:
list.shape

(2, 2)

In [45]:
list = np.arange(6)
list.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

### Indexing and Slicing

In [46]:
array = np.array([1, 2, 3, 4])
array[0]

1

In [47]:
array[0:2]

array([1, 2])

In [48]:
array[1:]

array([2, 3, 4])

In [49]:
array[:-2]

array([1, 2])

In [50]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[a > 6]

array([ 7,  8,  9, 10, 11, 12])

In [51]:
divisible5 = (a % 5 == 0)
a[divisible5]

array([ 5, 10])

In [55]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
array2 = array1[3:7]
array2


array([4, 5, 6, 7])

### Array Stacks

In [57]:
array1 = np.array([[1, 1], [2, 2]])
array2 = np.array([[3, 3], [4, 4]])
np.hstack((array1, array2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [58]:
np.vstack((array1, array2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

### Copy

In [59]:
array3 = array2.copy()
array3

array([[3, 3],
       [4, 4]])

### Array Operations

In [60]:
a = np.array([1, 2])
b = np.array([3, 4])
a + b

array([4, 6])