In [2]:
import numpy as np
import pandas as pd

In [3]:
list = [1, 2, 3]
array = np.array(list)
print(array)

[1 2 3]


In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [13]:
sorter = np.array([4, 3, 2, 1])
np.sort(sorter)

array([1, 2, 3, 4])