In [1]:
import numpy as np
import pandas as pd

### Initialize Numpy Array

In [2]:
list = [1, 2, 3]
array = np.array(list)
array

array([1, 2, 3])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

### Sort Array

In [7]:
sorter = np.array([4, 3, 2, 1])
np.sort(sorter)

array([1, 2, 3, 4])

### Concatenate Arrays

In [8]:
l1 = np.array([1, 2, 3])
l2 = np.array([4, 5, 6])
np.concatenate((l1, l2), axis=0)

array([1, 2, 3, 4, 5, 6])

### Shape, Size, Reshape

In [9]:
list = np.array([[1, 2], [3, 4]])
list.ndim

2

In [10]:
list.size

4

In [11]:
list.shape

(2, 2)

In [12]:
list = np.arange(6)
list.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

### Indexing and Slicing

In [13]:
array = np.array([1, 2, 3, 4])
array[0]

1

In [14]:
array[0:2]

array([1, 2])

In [15]:
array[1:]

array([2, 3, 4])

In [16]:
array[:-2]

array([1, 2])

In [17]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[a > 6]

array([ 7,  8,  9, 10, 11, 12])

In [18]:
divisible5 = (a % 5 == 0)
a[divisible5]

array([ 5, 10])

In [19]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
array2 = array1[3:7]
array2


array([4, 5, 6, 7])

### Array Stacks

In [20]:
array1 = np.array([[1, 1], [2, 2]])
array2 = np.array([[3, 3], [4, 4]])
np.hstack((array1, array2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [21]:
np.vstack((array1, array2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

### Copy

In [22]:
array3 = array2.copy()
array3

array([[3, 3],
       [4, 4]])

### Array Operations

In [28]:
a = np.array([1, 2])
b = np.array([3, 4])
a + b

array([4, 6])

In [29]:
(3 * a) + (b - 4)

array([2, 6])